import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * A marketing page rendered from the designer's handoff markup.
 *
 * ## Why this is not converted to JSX
 *
 * `Smallfish_Handoff.zip` (2026-10-04) states it plainly: *"the two HTML files
 * in `pages/` are the specification: they are self-contained, they run, and
 * they are correct. If this document and the files disagree, the files win."*
 *
 * The home page is 104 KB of hand-tuned markup carrying **28 inline SVGs** —
 * a tiled fish pattern, a 545px outline fish, a dot-grid US map with eight
 * addressable city groups, flowing currents, three logo lockups — all
 * generated by the designer's own `build_home.py`. Retyping that as JSX would
 * mean a four-figure number of hand edits whose only possible outcomes are
 * "identical" or "worse", and the failure mode of a transcription error in an
 * SVG path is a shape that is subtly wrong and that nobody notices.
 *
 * So the markup is served as authored. React never diffs the contents of
 * `dangerouslySetInnerHTML`, which is also what makes the handoff's own
 * scripts safe to run against it: they own that subtree outright.
 *
 * **On `dangerouslySetInnerHTML`:** the input is a file in this repository,
 * written by us, read at build time. It is never user input and never reaches
 * this component from a request. That is the whole of the risk assessment.
 *
 * ## What was changed from the handoff, and why
 *
 * 1. **Hrefs** to this repo's real routes — the handoff's `/signup`, `/signin`,
 *    `/remove`, `/how-we-crawl` and `/what-we-get-wrong` do not exist here.
 *    `/sign-up` keeps `?source=home`, because without it every direct sign-up
 *    is indistinguishable from one a channel earned (`doors.ts`).
 * 2. **Six global CSS rules scoped to `.sf-site`** — `:root`, `body`, `a` and
 *    `img,svg`. `globals.css` already owns `body` at the same specificity, so
 *    leaving them global would have made the result depend on stylesheet
 *    order, which is the kind of thing that works until it silently does not.
 * 3. **Two sentences and three numbers** — see the commit. The handoff said
 *    "we open every one of their websites", and `CLAUDE.md` records "every" as
 *    the one word this product cannot use.
 *
 * ## Keeping the no-JavaScript polarity
 *
 * HANDOFF §3.7: every reveal defaults to visible and is *hidden* by `.js` only
 * after the script runs, so the page is whole for a crawler. The script adds
 * `js` to `documentElement` on its first line and the stylesheet keys its
 * reveals off `.js .rise`. Serving the script `defer` preserves that exactly:
 * it executes after parsing, so nothing is ever hidden before it can be
 * revealed again.
 */

const FONTS =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT@0,9..144," +
  "300..700,0..100;1,9..144,300..700,0..100&family=IBM+Plex+Mono:wght@400;500;600" +
  "&family=IBM+Plex+Sans:wght@400;500;600&display=swap";

const GSAP = "https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5";

export default async function HandoffPage({ file }: { file: string }) {
  const html = await readFile(
    path.join(process.cwd(), "src", "app", "_handoff", file),
    "utf8",
  );

  return (
    <>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link rel="stylesheet" href={FONTS} />
      <link rel="stylesheet" href="/handoff/site.css" />

      <div className="sf-site" dangerouslySetInnerHTML={{ __html: html }} />

      {/* Order matters and `defer` guarantees it: deferred scripts run in
          document order after parsing. The page checks `window.gsap` and falls
          back to IntersectionObserver reveals, so a blocked CDN costs the
          scroll-scrubbed arrival and nothing else (HANDOFF §9). */}
      <script src={`${GSAP}/gsap.min.js`} defer />
      <script src={`${GSAP}/ScrollTrigger.min.js`} defer />
      <script src="/handoff/site.js" defer />
    </>
  );
}
