/**
 * The facts both halves of the product state, stated the same way.
 *
 *     npm run build && node stage0/tests/test_contract.mjs
 *
 * ## Why this file exists
 *
 * The work is split across two streams that do not share a session: **GTM**
 * owns the marketing pages and **Product** owns the app (`docs/STREAMS.md`).
 * Most of the repository divides cleanly between them. A handful of facts do
 * not: the free allowance, what a credit buys, how many businesses were read,
 * what the engine can prove. Both halves say those out loud, to the same
 * person, often on the same visit.
 *
 * A number that disagrees across the seam is not a cosmetic bug here. The whole
 * argument of this product is that its figures are measured, and a home page
 * promising twenty free beside an app offering ten is the one failure that
 * cannot be explained away.
 *
 * ## What it checks, and why each one is a real hole and not a hypothetical
 *
 * 1. **The free allowance.** `/pricing` reads `PLANS` and cannot drift.
 *    `src/app/_handoff/home.html` is a designer's HTML file with `20` typed
 *    into it in three places, and the port that produced it only runs when a
 *    new handoff arrives. So changing `PLANS.free.credits` today silently makes
 *    the home page lie, and nothing anywhere notices.
 * 2. **The market figures.** `public/data` is regenerated by the Product
 *    stream; the home page's demo reel was written into it by the port. The
 *    same regeneration moves `/find`, `/markets` and `/benchmark`.
 * 3. **What we claim to prove.** `signals.ts` carries `provable: false` on
 *    entries the engine cannot settle. No marketing page may sell one.
 * 4. **Who sends.** "We never send anything" is a promise, not a feature
 *    description, and it is the one sentence that must survive both streams.
 *
 * ## What it deliberately does not check
 *
 * Tone, layout, wording. Those are each stream's own business, and a test that
 * polices them would be a standing argument between two sessions rather than a
 * guard against a lie.
 *
 * It reads the **prerendered** HTML, like `test_home_copy.mjs`, because a check
 * against source would pass on a number in a comment and fail on one that never
 * reaches a visitor.
 */

import { existsSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";
import { compileLib } from "./_tsmodules.mjs";

const OUT = path.join(process.cwd(), ".next", "server", "app");

if (!existsSync(path.join(OUT, "index.html"))) {
  console.error(
    "No prerendered pages. Run `npm run build` first — this test checks the\n" +
      "rendered HTML, not the source, and there is nothing to check without it.",
  );
  process.exit(2);
}

const { dir, load } = compileLib(
  ["src/lib/pricing.ts", "src/lib/signals.ts", "src/lib/types.ts"],
  "sfc-",
);
const P = await load("pricing");
const S = await load("signals");

let failures = 0;
const check = (name, cond, detail = "") => {
  if (cond) console.log(`  pass  ${name}`);
  else {
    failures += 1;
    console.log(`  FAIL  ${name}${detail ? ": " + detail : ""}`);
  }
};

/** Visible words only: a figure inside a `<script>` payload or an SVG path is
 *  not something a visitor reads. */
const text = (file) => {
  const p = path.join(OUT, file);
  if (!existsSync(p)) return null;
  const raw = readFileSync(p, "utf8");
  const stripped = raw.replace(/<(script|style|svg)\b[\s\S]*?<\/\1>/g, " ");
  return stripped
    .replace(/<[^>]+>/g, " ")
    .replace(/&[a-z]+;|&#\d+;/gi, " ")
    .replace(/\s+/g, " ");
};

const PAGES = {
  home: "index.html",
  pricing: "pricing.html",
  benchmark: "benchmark.html",
  markets: "markets.html",
  templates: "templates.html",
  howWeCheck: "how-we-check.html",
  why: "why-it-exists.html",
  compare: "compare.html",
};
const rendered = Object.fromEntries(
  Object.entries(PAGES).map(([k, f]) => [k, text(f)]).filter(([, v]) => v),
);
const everywhere = Object.values(rendered).join(" ");

/* -------------------------------------------------------------------------
 * 1 · the free allowance
 *
 * `PLANS` is the one place it is decided. Every page that names it has to name
 * the same number — and at least one page has to name it, or the offer the
 * whole funnel is built on has quietly stopped being made.
 * ---------------------------------------------------------------------- */
{
  const grant = P.PLANS.find((p) => p.id === "free")?.credits;
  check("the free plan has a grant to agree about", typeof grant === "number" && grant > 0, `${grant}`);

  // Every "N free" / "first N are free" claim on the marketing pages.
  const claims = [];
  for (const [page, body] of Object.entries(rendered)) {
    for (const re of [
      /\b(\d+)\s+businesses\s+free\b/gi,
      /\bfirst\s+(\d+)\s+(?:are\s+)?free\b/gi,
      /\b(\d+)\s+free(?:,|\s+businesses)?\s*(?:·|,)?\s*no card\b/gi,
    ]) {
      for (const m of body.matchAll(re)) claims.push({ page, n: Number(m[1]), said: m[0].trim() });
    }
  }

  check(
    "the marketing pages still make the free offer somewhere",
    claims.length > 0,
    "no page states a free allowance at all",
  );
  const wrong = claims.filter((c) => c.n !== grant);
  check(
    `and every one of them says ${grant}, the number in PLANS`,
    wrong.length === 0,
    wrong.map((c) => `${c.page}: "${c.said}"`).join(" | "),
  );

  // `/pricing` reads PLANS directly, so it is the control: if it disagrees,
  // the fault is in this test rather than in the copy.
  check(
    "and the pricing table, which reads PLANS directly, agrees",
    (rendered.pricing ?? "").includes(String(grant)),
    `${grant} not found on /pricing`,
  );
}

/* -------------------------------------------------------------------------
 * 1b · what money buys
 *
 * `/pricing` renders from `PLANS` and cannot drift. The home page's price slab
 * is markup, and it said **"$29 a month · up to 300"** against a Starter plan
 * of 120 credits. A match costs 1, 2 or 3 credits (`BANDS`), so credits are the
 * ceiling on matches and 300 is unreachable at any band. Every tier was wrong
 * the same way — 300/1,000/3,000 against 120/400/1,000 — and the two pages sat
 * one click apart disagreeing by 2.5x about what money buys.
 *
 * A plan may of course promise *fewer* matches than its credits allow. It may
 * never promise more.
 * ---------------------------------------------------------------------- */
{
  const paid = P.PLANS.filter((p) => p.priceUsd > 0 && !["pack", "watch"].includes(p.id));
  check("there are paid plans to check", paid.length >= 3, `${paid.length}`);

  // "$29 ... up to 300" — the price and its allowance, however much markup
  // sits between them.
  const home = rendered.home ?? "";
  const promises = [...home.matchAll(/\$(\d+)\s*(?:a month)?\s*up to\s+([\d,]+)/gi)].map((m) => ({
    usd: Number(m[1]),
    upTo: Number(m[2].replace(/,/g, "")),
    said: m[0].replace(/\s+/g, " ").trim(),
  }));
  check("the home page still states a price slab", promises.length > 0, "no '$N ... up to M' found");

  const over = promises.filter((q) => {
    const plan = paid.find((p) => p.priceUsd === q.usd);
    // A price the plans do not have is its own problem, caught below.
    return plan ? q.upTo > plan.credits : false;
  });
  check(
    "no plan promises more matches than its credits can buy",
    over.length === 0,
    over
      .map((q) => {
        const plan = paid.find((p) => p.priceUsd === q.usd);
        return `"${q.said}" but ${plan.name} is ${plan.credits} credits, and a match costs at least 1`;
      })
      .join(" | "),
  );

  const unknown = promises.filter((q) => !paid.some((p) => p.priceUsd === q.usd));
  check(
    "and every price on the home page is a plan that exists",
    unknown.length === 0,
    unknown.map((q) => q.said).join(" | "),
  );
}

/* -------------------------------------------------------------------------
 * 2 · the market figures
 *
 * Regenerating `public/data` is Product's job and moves every marketing page
 * that quotes a market. The home page's demo reel is the exposed one: the port
 * wrote those figures in and only runs when a new handoff arrives.
 * ---------------------------------------------------------------------- */
{
  const idx = JSON.parse(
    readFileSync(path.join(process.cwd(), "public", "data", "index.json"), "utf8"),
  );

  // The demo reel lives in `public/handoff/site.js` — the port writes the
  // figures into the designer's script, not into the markup — so stripping
  // `<script>` from the rendered page (which this file does, deliberately,
  // because a figure in a payload is not something a visitor reads) hides
  // exactly the numbers that can go stale. Read the reel at its source.
  const reel = readFileSync(path.join(process.cwd(), "public", "handoff", "site.js"), "utf8");
  const rows = [...reel.matchAll(/to: '([^']*)', n: (\d+)[^}]*?read: (\d+)/g)].map((m) => ({
    to: m[1],
    fit: Number(m[2]),
    read: Number(m[3]),
  }));
  check("the home page's demo reel still has rows to check", rows.length >= 3, `${rows.length}`);

  for (const row of rows) {
    const city = row.to.split(" in ").pop().trim();
    const market = idx.markets.find((m) => m.metro.split(",")[0].trim() === city);
    check(`the reel's ${city} market is one we still carry`, !!market, row.to);
    if (!market) continue;

    const fit = Math.max(...market.criteria.map((c) => market.tallies?.[c.id]?.match ?? 0));
    check(
      `and its ${city} count is the measured ${fit}`,
      row.fit === fit,
      `reel says ${row.fit} — re-run stage0/src/site/port_handoff.py after regenerating public/data`,
    );
    check(
      `and its ${city} read figure is the measured ${market.counts.withSite}`,
      row.read === market.counts.withSite,
      `reel says ${row.read}`,
    );
  }

  // Every four-digit figure the home page states must be one `public/data`
  // can produce.
  //
  // This is the check that would have caught `3,041 dentists in Phoenix`,
  // which was live on production. It is in no data file — `3041` occurs in
  // `public/data` only inside latitude digits — and it survived an earlier
  // fix that replaced the *same invented number* in the counter beside it,
  // because that edit matched on markup the reel's sub-line does not use.
  //
  // Figures are matched against the measured counts of every market, not just
  // the one named, because a page may legitimately quote any of them. What it
  // may not do is quote a number no market has.
  {
    const allowed = new Set();
    for (const m of idx.markets) {
      for (const v of Object.values(m.counts)) allowed.add(v);
      for (const t of Object.values(m.tallies ?? {})) {
        for (const v of Object.values(t)) allowed.add(v);
      }
    }
    // Years, prices and the free grant are not market sizes.
    const notACount = new Set([2026, 2025, 1000, ...P.PLANS.map((p) => p.credits), ...P.PLANS.map((p) => p.priceUsd)]);

    const stated = [
      ...(rendered.home ?? "").matchAll(/\b(\d{1,2},\d{3})\b/g),
    ].map((m) => Number(m[1].replace(/,/g, "")));

    const invented = [...new Set(stated)].filter((n) => !allowed.has(n) && !notACount.has(n));
    check(
      "every thousands figure on the home page is one the data can produce",
      invented.length === 0,
      `${invented.join(", ")} appear in no market's counts or tallies`,
    );
  }

  check(
    "the index still carries tallies for every market",
    idx.markets.every((m) => m.criteria.every((c) => m.tallies?.[c.id])),
  );
}

/* -------------------------------------------------------------------------
 * 3 · we only sell what the engine can settle
 *
 * `signals.ts` is Product's. `provable: false` is not a to-do — it is the
 * record of a criterion the engine refuses. A marketing page selling one is
 * the product promising work it declines to do.
 * ---------------------------------------------------------------------- */
{
  const unprovable = S.SIGNALS.filter((s) => !s.provable);
  check("there are unprovable signals to guard against", unprovable.length > 0, `${unprovable.length}`);

  // The label alone is too loose — "a contact form" appears in honest sentences
  // about what we cannot tell. What may not appear is a *sales* claim built on
  // one: find/show me/businesses with.
  const sold = [];
  for (const s of unprovable) {
    const label = s.label.replace(/^an? /i, "");
    const re = new RegExp(
      `(find|show you|tell you which|businesses (?:that|with)|list of)[^.]{0,40}${label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`,
      "i",
    );
    // Naming an unprovable signal is not selling it — `/templates` lists each
    // one precisely so an omission does not read as "we never thought of it",
    // and says "Not settled today" in the next breath. What is forbidden is
    // the claim standing alone. So the refusal has to be missing from the
    // sentence around it before this counts.
    const hit = [];
    for (const [page, body] of Object.entries(rendered)) {
      for (const m of body.matchAll(new RegExp(re.source, "gi"))) {
        const near = body.slice(m.index, m.index + 320);
        const refused = /not settled|can.?t settle|cannot settle|would need|not yet|we do not|couldn.?t tell/i.test(near);
        if (!refused) hit.push(page);
      }
    }
    if (hit.length) sold.push(`${s.id} on ${[...new Set(hit)].join(", ")}`);
  }
  check(
    "no marketing page sells a signal the engine cannot settle",
    sold.length === 0,
    sold.join(" | "),
  );

  // And the templates library, which is derived from the catalogue, still says
  // out loud that some asks cannot be run.
  check(
    "the templates page still names what it cannot prove",
    !rendered.templates || /can.?t|cannot|not yet|would need/i.test(rendered.templates),
  );
}

/* -------------------------------------------------------------------------
 * 4 · the promises that outlive either stream
 * ---------------------------------------------------------------------- */
{
  check(
    "the site still says we never send",
    /never send|you send it/i.test(everywhere),
    "the one sentence that distinguishes this from a sending tool",
  );
  check(
    "and still offers a way out for a business that wants off",
    /opt out|remove (?:my|your) business|stop (?:reading|crawling)/i.test(everywhere) ||
      existsSync(path.join(OUT, "opt-out.html")),
  );
  // "every" is the word this product cannot use: 200 of 2,778 were read.
  // Must be **us** claiming it, and must not be a denial.
  //
  // A first cut matched the word "every" and fired on `/terms` — *"We do not
  // promise to have read every business in an area"* — and on `/compare`,
  // where it describes what a bulk exporter does. Both are the opposite of an
  // overclaim: one is the disclaimer, the other is the competitor. A guard
  // that flags the disclaimer trains everyone to ignore it.
  const overclaim = [];
  for (const [page, body] of Object.entries(rendered)) {
    for (const m of body.matchAll(/\b(we(?:'ve| have)? (?:read|checked|opened))[^.]{0,30}\bevery\b[^.]{0,40}/gi)) {
      const before = body.slice(Math.max(0, m.index - 60), m.index);
      if (/do not|don.?t|never|cannot|can.?t|not\s*$/i.test(before)) continue;
      overclaim.push(`${page}: "${m[0].trim()}"`);
    }
  }
  check("and claims total coverage nowhere", overclaim.length === 0, overclaim.join(" | "));
}

rmSync(dir, { recursive: true, force: true });
console.log(`\n${failures} failure(s)`);
process.exit(failures ? 1 : 0);
