-- A list a customer shares, and the credit for whoever opens it.
--
-- The flow document's read-only shared view, and the GTM plan's referral loop
-- are the same object: a customer sends somebody a list they are proud of, the
-- recipient sees three of it in full and signs up for the rest, and the sharer
-- gets the credit. `docs/LAUNCH.md` listed them as two separate missing things;
-- they are one table.
--
-- ## The token is the capability
--
-- Anybody with the link can open it, and that is the point — it travels in a
-- Slack message and an email forward. So the token is the whole permission, and
-- two things follow:
--
--   - It is generated by the database, from `gen_random_bytes`, not by an
--     application that might seed a PRNG badly. Sixteen bytes, base64url, which
--     is not guessable by anybody willing to spend a weekend on it.
--   - It is revocable. A link somebody cannot take back is a link they will not
--     send, and "I shared that with the wrong person" has to have an answer.
--
-- ## What a shared list is allowed to show
--
-- Exactly what every other unpaid surface shows: the count, the reasons, and
-- the **first three matches in full**. Not the sharer's whole paid list — the
-- rows they unlocked are theirs, not theirs to redistribute, and a share link
-- that handed over forty paid businesses would make the paywall a formality for
-- anybody with one friend.
--
-- Nothing about *which* rows is stored here. The page derives them with
-- `matchedIn` and `visibleIds`, the same functions the results screen uses, so
-- a shared list cannot drift from the product.

create table if not exists public.shared_lists (
  -- base64**url**. Plain base64 emits `+`, `/` and `=`, and this string's only
  -- job is to sit in a URL: `/` would split the path, `+` decodes to a space
  -- through some clients, and `=` needs escaping. Translated once here rather
  -- than sanitised at every place that builds or reads a link.
  token        text primary key
               default translate(encode(gen_random_bytes(16), 'base64'), '+/=', '-_')
               check (token ~ '^[A-Za-z0-9_-]{16,64}$'),
  account_id   uuid not null references public.accounts (id) on delete cascade,
  market_id    text not null,
  criterion_id text not null,
  /** What the sharer called it, for the page's kicker. */
  label        text,
  created_at   timestamptz not null default now(),
  revoked_at   timestamptz,
  /** Opens. The sharer's own number, and the only reason to come back to the
   *  share screen at all. */
  views        integer not null default 0 check (views >= 0)
);

comment on table public.shared_lists is
  'Read-only links to a list. The token is the capability; revoked_at withdraws it.';

create index if not exists shared_lists_account_idx
  on public.shared_lists (account_id, created_at desc);

alter table public.shared_lists enable row level security;

-- The sharer can see their own links. **Nobody reads this table by token** —
-- the page resolves a token with the service role, because a policy that let a
-- client select by token would let a client enumerate every token.
drop policy if exists shared_lists_read on public.shared_lists;
create policy shared_lists_read on public.shared_lists
  for select using (public.member_of (account_id));

revoke insert, update, delete on public.shared_lists from anon, authenticated;
revoke all on public.shared_lists from anon;
grant select on public.shared_lists to authenticated;

/**
 * Make a link, or hand back the one that already exists.
 *
 * Idempotent per (account, market, criterion): pressing Share twice produces
 * one link, not two. Two links to the same list is a customer wondering which
 * one they sent, and two rows of view counts that each tell half the story.
 *
 * A previously revoked link stays revoked — un-revoking by pressing Share again
 * would make "revoke" mean "until you forget".
 */
create or replace function public.share_list (
  p_account uuid,
  p_market text,
  p_criterion text,
  p_label text default null
) returns public.shared_lists
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.shared_lists;
begin
  select * into v_row
    from public.shared_lists
   where account_id = p_account
     and market_id = p_market
     and criterion_id = p_criterion
     and revoked_at is null
   limit 1;

  if v_row.token is not null then
    return v_row;
  end if;

  insert into public.shared_lists (account_id, market_id, criterion_id, label)
  values (p_account, p_market, p_criterion, nullif(btrim(coalesce(p_label, '')), ''))
  returning * into v_row;

  return v_row;
end;
$$;

/** Resolve a token, and count the open. Returns nothing for a revoked link. */
create or replace function public.open_shared_list (p_token text)
returns public.shared_lists
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.shared_lists;
begin
  update public.shared_lists
     set views = views + 1
   where token = p_token and revoked_at is null
  returning * into v_row;

  return v_row;
end;
$$;

/** Withdraw a link. The row stays, so the view count it earned is not lost. */
create or replace function public.revoke_shared_list (p_account uuid, p_token text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_n integer;
begin
  update public.shared_lists
     set revoked_at = now()
   where token = p_token and account_id = p_account and revoked_at is null;
  get diagnostics v_n = row_count;
  return v_n = 1;
end;
$$;

revoke all on function public.share_list (uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.open_shared_list (text) from public, anon, authenticated;
revoke all on function public.revoke_shared_list (uuid, text) from public, anon, authenticated;

grant execute on function public.share_list (uuid, text, text, text) to service_role;
grant execute on function public.open_shared_list (text) to service_role;
grant execute on function public.revoke_shared_list (uuid, text) to service_role;
